# 编写相关基本信息
db_1:
  db_host: "211.103.136.242"
  db_user: "test"
  db_password: "test123456"
  db_name: "meiduo"
  db_charset: "utf8"
  db_port: 7090


db_2:
  db_host: "311.103.136.242"
  db_user: "test"
  db_password: "test123456"
  db_name: "meiduo"
  db_charset: "utf8"
  db_port: 7090

